### ISSUE TITLE
希望增加一个变量来设置是否使用分流路由表或者是所有流量都走VPN

### ISSUE THREAD

**Issue by esme518** [TommyLau/docker-ocserv#12]
希望增加一个变量来设置是否使用分流路由表或者是所有流量都走VPN 谢了

**Comment by TommyLau** [comment]
是在 Docker 命令的环境变量里面，还是说配置文件里面？

**Comment by esme518** [comment]
环境变量就是类似于NO_TEST_USER这样的

**Comment by TommyLau** [comment]
如果要用环境变量的话，就得写一些小脚本来控制了。

**Comment by s7lx** [comment]
openconnect实现了anyconnect的用户分组。两个分组可以实现两个不同的路由表。一个分组走分流一个分组走全局。回头提pr给你

**Comment by TommyLau** [comment]
骚年，你竟然还有关注这个project？这不科学~

**Comment by s7lx** [comment]
给我开个权限，我直接提交代码进去吧😝

**Comment by TommyLau** [comment]
Invitation sent.

**Comment by s7lx** [comment]
@esme518 来试试吧。已经可以走路由表或者全局走VPN了。不过是通过用户分组实现的。登陆的时候注意一下
