### ISSUE TITLE
请问这个Docker能够支持IPV6么？

### ISSUE THREAD

**Issue by RoyLi-Pvt** [TommyLau/docker-ocserv#13]
我家的环境是Openwrt通过HE的6in4隧道接入IPV6网络并作为默认翻墙方案的，最近联通的手机网络劫持严重于是想通过这个docker直接连到家里顺带翻墙，但是连接上之后似乎并不能通过IPV6直接翻墙

**Comment by TommyLau** [comment]
理论上支持，可以参考：https://www.v2ex.com/t/234058

要打开 IPv6 forwarding

**Comment by RoyLi-Pvt** [comment]
doucker镜像本身不需要进行修改么 IPV6的地址池什么的V2那个帖子也提到了 我家服务器本身转发是打开的 但是连接上之后IPV6地址显示为Disabled

**Comment by TommyLau** [comment]
可能需要修改 ocserv.conf 文件，这个用 docker 映射出来就好了。

**Comment by RoyLi-Pvt** [comment]
我 修改了dockerfile和docker-entrypoint.sh添加了相关的配置 这样能够获取IPv6地址了 DNS也能得到IPV6结果，但是还是无法访问google是不是默认路由之类的需要改一下？我现在去掉了Dockerfile里面所有关于路由表配置的语句 删掉了68-71行

**Comment by TommyLau** [comment]
你参考下这个：
https://docs.docker.com/engine/userguide/networking/default_network/ipv6/

主要是 sysctl 部分：
$ sysctl net.ipv6.conf.default.forwarding=1
$ sysctl net.ipv6.conf.all.forwarding=1

**Comment by RoyLi-Pvt** [comment]
然而我非常确定这两个配置不论是在宿主机还是docker都已经是改过的了
docker文档中提到的--ipv6也加上了

**Comment by TommyLau** [comment]
sysctl 完了要使之生效才可以的，光执行是不行的。

**Comment by RoyLi-Pvt** [comment]
额这种入门问题就不用提醒我了233333333我非常确定这两个配置已经生效了 在服务器上我执行过了 sysctl -p 的而docker上我是直接改的docker-entrypoint.sh文件并重新build的 所以这两个配置肯定已经生效了

**Comment by TommyLau** [comment]
那确实不确认，手上没有 IPv6 的条件做测试，或者去 ocserv 那里问问？
