### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by SquirrelCoder** [TommyLau/docker-ocserv#15]
Hello Sir,

Thanks for your outstanding work. could you please guide me, how to change the port? Unfortunately my port 443 is used for something else.

Thanks

**Comment by TommyLau** [comment]
Unfortunately, you cannot if you are using AnyConnect as the client. But you can use other proxy server to detect what protocol is being used and then forward them to different services.

If you are not using AnyConnect as the client, then you can change the ocserv.conf to specific a new port.

This site might help:
http://www.infradead.org/ocserv/multihost.html
