### ISSUE TITLE
There's nothing happend after input username and password

### ISSUE THREAD

**Issue by sjc2000** [TommyLau/docker-ocserv#16]
I have input test test and anyconnect client return back to first screen prompt input username password again. Please help thx.

**Comment by TommyLau** [comment]
Can you be a little bit specific for the system, configuration, docker version, image version and etc?

**Comment by sjc2000** [comment]
Thanks for reply. 
The system is CentOS Linux 7 (Core) installed on vm, Kernel 3.10.0-327.36.3.el7.x86_64. Docker version 1.12.3, image version latest. Client Cisco Anyconnect version 4.0.00048. If I input wrong password it reply error password, so the network and service is working.

**Comment by TommyLau** [comment]
I've tried but cannot reproduce this issue, my configuration:
- Ubuntu 16.04 LTS with Kernel 3.13.0
- Docker 1.12.1
- Anyconnect 4.3.02039

I suggest you have the Anyconnect client upgraded to latest version and then have another try first. Also check the permissions of firewalls of both server / client.

Administrators privileges might be needed as the TAP/TUN, as your describe, mostly it could be the problem from the client side, but not the server side.

**Comment by sjc2000** [comment]
Thanks, I'll try that again.

**Comment by TommyLau** [comment]
OK
