### ISSUE TITLE
Question: how can I add valid certificate?

### ISSUE THREAD

**Issue by hadifarnoud** [TommyLau/docker-ocserv#18]
how can I add a valid certificate in order to get rid of 'untrusted server' errors?

what are Route and All proxy groups mean? does it mean you can exclude .cn domains from VPN?

**Comment by TommyLau** [comment]
You can run with the '-v' opinion with docker and point the `/etc/ocserv` to your host's path, and you can add / edit your own config file.

**Comment by hadifarnoud** [comment]
I have difficulty with CA. used this command:
`docker run --name ocserv --privileged -p 443:443 -p 443:443/udp -e SRV_CN=my.test.com -e SRV_ORG="My Test" -e SRV_DAYS=365 -d tommylau/ocserv`

I changed `SRV_CN` to my domain name. but Cisco Anyconnect is still saying 'certificate does not match server name' and I can't connect.

**Comment by TommyLau** [comment]
You have to have a valid signed certificate from those authorities.

The one from command line is self-signed only.

**Comment by hadifarnoud** [comment]
thanks, I've followed [this tutorial](http://clusterfrak.com/sysops/app_installs/openvpn_install/#download-ocserv). it was a bit outdated but managed to fix the issues and now have valid certificate. maybe you can update your README and add support for Letsencrypt?

**Comment by TommyLau** [comment]
I'd love to, but it will be a little bit over what `ocserv` can do, certificate should not be considered as part of it.

**Comment by hadifarnoud** [comment]
It could be nice to have that optional step. It makes your image super useful 

a, pre, code, a:link, body { word-wrap: break-word !important; }
