### ISSUE TITLE
how to enable debug modle ?

### ISSUE THREAD

**Issue by macaty** [TommyLau/docker-ocserv#31]
how to enable debug modle with docker run ?

**Comment by TommyLau** [comment]
You mean ocserv's debug output?

```
docker run tommylau/ocserv ocserv -c /etc/ocserv/ocserv.conf -f -d 9999
```

You can use your own configuration, above is an example.

You can refer to the [manual](https://ocserv.gitlab.io/www/manual.html) from ocserv.

**Comment by macaty** [comment]
thx it works
