### ISSUE TITLE
如何 修改/自定义 ocserv.conf 的内容，主要是想配置路由表

### ISSUE THREAD

**Issue by chenglu** [TommyLau/docker-ocserv#4]
想修改一下配置的路由表，比如我大1024切换到 cloudflare 之后，cloudflare 的 IP 段就需要代理了 ;)

**Comment by TommyLau** [comment]
可以使用 -v 命令来将物理机的目录映射到 docker 中，比如 /data/ocserv:/etc/ocserv

docker run --name ocserv -v /data/ocserv:/etc/ocserv .......

把 /data/ocserv 换成你物理机的路径，然后吧 ocserv.conf 相关的文件放在那里就可以了。

**Comment by chenglu** [comment]
万分感谢 ；）
