### ISSUE TITLE
Server certificate verify failed: signer not found

### ISSUE THREAD

**Issue by mehrancodes** [TommyLau/docker-ocserv#43]
Hello @TommyLau.

I pulled this image on a fresh ubuntu 16.04 server and just initialized it with the test username, but when I try to connect to the server through the openconnect on Ubuntu 16.04, it shows this log:

```
POST https://206.*.*.*/
Attempting to connect to server 206.*.*.*:443
SSL negotiation with 206.*.*.*
Server certificate verify failed: signer not found
SSL connection failure: The operation timed out
Failed to open HTTPS connection to 206.*.*.*
```

What's wrong?

**Comment by hos7ein** [comment]
Could you please put it your command here?
Note: To keep your server security, hide your Server IP.

**Comment by mehrancodes** [comment]
@hos7ein Hello, thanks to response.
I used this command after pulling the image

docker run --name ocserv --privileged -p 443:443 -p 443:443/udp -d tommylau/ocserv

But when I added a new openconnect connection on my system with my server ip address, it can't connect and fails.

**Comment by hos7ein** [comment]
Actually your command is correct and I tested it, but I think you make a wrong on openconnect client connection. Check out again your openconnect client connection.

**Comment by mehrancodes** [comment]
I found out that it is because of the service provider's proxy I use.

@hos7ein Thanks for your response
