### ISSUE TITLE
移除 MAX_CONFIG_ENTRIES 调整

### ISSUE THREAD

**Issue by CzBiX** [TommyLau/docker-ocserv#5]
根据此从 [commit](http://git.infradead.org/ocserv.git/commit/a5b2175219f3a45a1135eed3ce307d308ad98200)，从 ocserv 0.10.6 开始不再使用 `MAX_CONFIG_ENTRIES`，有多少条规则生效取决于客户端的限制。
所以 [Dockerfile#L47](https://github.com/TommyLau/docker-ocserv/blob/master/Dockerfile#L47) 可以被移除了，#1 也没有意义了。

**Comment by TommyLau** [comment]
Thanks for leaving this message, I'll grep the new source form OpenConnect and change the Dockerfile accordingly.

**Comment by TommyLau** [comment]
Changed Dockerfile and entry shell script to work with latest version (0.10.9) of ocserv.
